include("candidate_reconstruction.jl")
TestbedCandidateReconstruction.self_test()
include("casa_c_reconstruction.jl")
TestbedCASACReconstruction.self_test()
include("mimics_c_reconstruction.jl")
TestbedMIMICSCReconstruction.self_test()
