module TestbedReferencePublication

import Pkg
import SHA
import TOML

const MODELS = ("CORPSE", "MIMICS-C", "MIMICS-CN", "CASA-C", "CASA-CN")
const CANONICAL_TOOLCHAIN_IDENTITY = "climaland-biogeochem-reference-linux-gfortran-v1"
const CANONICAL_BUILD_PLATFORM = "x86_64-linux-gnu"
const DEFAULT_ARTIFACTS_TOML =
    joinpath(@__DIR__, "validation", "Artifacts.toml")
const BINDINGS = Dict(
    "CORPSE" => "representative_corpse_reference",
    "MIMICS-C" => "representative_mimics_c_reference",
    "MIMICS-CN" => "representative_mimics_cn_reference",
    "CASA-C" => "representative_casa_c_reference",
    "CASA-CN" => "representative_casa_cn_reference",
)

struct PublicationError <: Exception
    message::String
end

Base.showerror(io::IO, error::PublicationError) = print(io, error.message)

fail(message) = throw(PublicationError(message))

sha256sum(path) =
    open(path) do io
        bytes2hex(SHA.sha256(io))
    end

function parse_toml(path, description)
    isfile(path) || fail("$description is missing at $path")
    islink(path) && fail("$description must not be a symbolic link")
    try
        return TOML.parsefile(path)
    catch error
        fail("$description is unreadable: $(sprint(showerror, error))")
    end
end

valid_sha256(value) =
    value isa AbstractString && occursin(r"^[0-9a-f]{64}$", value)
valid_revision(value) =
    value isa AbstractString &&
    occursin(r"^(?:[0-9a-f]{40}|[0-9a-f]{64})$", value)

function validate_hashes(values, description)
    values isa AbstractDict && !isempty(values) ||
        fail("$description must declare at least one SHA-256")
    all(
        pair ->
            pair.first isa AbstractString &&
                !isempty(pair.first) &&
                valid_sha256(pair.second),
        pairs(values),
    ) || fail("$description contains an invalid SHA-256")
    return Dict{String, String}(
        String(key) => String(value) for (key, value) in values
    )
end

function payload_files(payload)
    files = String[]
    for (root, directories, names) in walkdir(payload; follow_symlinks = false)
        for name in (directories..., names...)
            islink(joinpath(root, name)) &&
                fail("publication payloads must not contain symbolic links")
        end
        append!(files, relpath(joinpath(root, name), payload) for name in names)
    end
    sort!(files)
    return files
end

function compatibility_document(provenance)
    return Dict(
        "scope_manifest_sha256" => provenance["scope_manifest_sha256"],
        "forcing_sha256" => provenance["forcing_sha256"],
        "shared_parameter_sha256" => provenance["shared_parameter_sha256"],
        "comparison_schema" => provenance["comparison_schema"],
    )
end

function compatibility_identity(provenance)
    io = IOBuffer()
    TOML.print(io, compatibility_document(provenance); sorted = true)
    return bytes2hex(SHA.sha256(take!(io)))
end

function validate_provenance(provenance, description)
    provenance isa AbstractDict || fail("$description lacks provenance")
    valid_sha256(get(provenance, "scope_manifest_sha256", nothing)) ||
        fail("$description has an invalid Scope Manifest identity")
    forcing_sha256 = validate_hashes(
        get(provenance, "forcing_sha256", nothing),
        "$description forcing provenance",
    )
    shared_parameter_sha256 = validate_hashes(
        get(provenance, "shared_parameter_sha256", nothing),
        "$description shared-parameter provenance",
    )
    parameter_sha256 = validate_hashes(
        get(provenance, "parameter_sha256", nothing),
        "$description parameter provenance",
    )
    for key in (
        "comparison_schema",
        "compiler_identity",
        "build_platform",
        "toolchain_identity",
    )
        value = get(provenance, key, nothing)
        value isa AbstractString && !isempty(strip(value)) ||
            fail("$description lacks $key")
    end
    for key in ("source_revision", "generator_revision")
        valid_revision(get(provenance, key, nothing)) ||
            fail("$description has an invalid $key")
    end
    provenance["build_platform"] == CANONICAL_BUILD_PLATFORM &&
        provenance["toolchain_identity"] == CANONICAL_TOOLCHAIN_IDENTITY &&
        occursin("Fortran", provenance["compiler_identity"]) || fail(
        "$description was not generated by the canonical Linux/Fortran toolchain",
    )
    normalized =
        Dict{String, Any}(String(key) => value for (key, value) in provenance)
    normalized["forcing_sha256"] = forcing_sha256
    normalized["shared_parameter_sha256"] = shared_parameter_sha256
    normalized["parameter_sha256"] = parameter_sha256
    return normalized
end

function validate_payload(payload, kind, generation; model = nothing)
    isdir(payload) ||
        fail("$kind publication lacks a complete reference bundle")
    islink(payload) && fail("publication payloads must not be symbolic links")
    description = isnothing(model) ? kind : "$model reference"
    manifest_path = joinpath(payload, "manifest.toml")
    manifest = parse_toml(manifest_path, "$description manifest")
    get(manifest, "schema_version", nothing) == 1 ||
        fail("$description manifest has an incompatible schema")
    get(manifest, "kind", nothing) == kind ||
        fail("$description manifest declares the wrong bundle kind")
    get(manifest, "scope", nothing) == "representative" ||
        fail("$description manifest is not Representative")
    get(manifest, "generation", nothing) == generation ||
        fail("$description manifest belongs to a partially mixed generation")
    get(manifest, "outcome", nothing) == "passed" ||
        fail("$description fresh comparison did not pass")
    get(manifest, "canonical", nothing) === true || fail(
        "$description was not generated by the canonical Linux/Fortran toolchain",
    )
    if kind == "reference"
        get(manifest, "model", nothing) == model ||
            fail("$description manifest declares the wrong model")
    elseif haskey(manifest, "model")
        fail("forcing manifest must not declare a model")
    end
    provenance = validate_provenance(
        get(manifest, "provenance", nothing),
        "$description manifest",
    )
    declared_files = validate_hashes(
        get(manifest, "files", nothing),
        "$description manifest files",
    )
    actual_files = setdiff(payload_files(payload), ["manifest.toml"])
    sort!(collect(keys(declared_files))) == actual_files ||
        fail("$description manifest does not declare the complete bundle")
    for (relative_path, expected_sha256) in declared_files
        isabspath(relative_path) &&
            fail("$description manifest contains an unsafe file path")
        startswith(relative_path, "..") &&
            fail("$description manifest contains an unsafe file path")
        sha256sum(joinpath(payload, relative_path)) == expected_sha256 ||
            fail("$description bundle differs from its manifest")
    end
    normalized =
        Dict{String, Any}(String(key) => value for (key, value) in manifest)
    normalized["provenance"] = provenance
    normalized["files"] = declared_files
    return (;
        payload,
        kind,
        model,
        manifest = normalized,
        compatibility_identity = compatibility_identity(provenance),
    )
end

function validate_candidate(candidate_root)
    isdir(candidate_root) ||
        fail("publication candidate is missing at $candidate_root")
    candidate = parse_toml(
        joinpath(candidate_root, "publication_candidate.toml"),
        "publication candidate",
    )
    get(candidate, "schema_version", nothing) == 1 ||
        fail("publication candidate has an incompatible schema")
    get(candidate, "operation", nothing) == "reference_publication" ||
        fail("ordinary fresh runs are not publication candidates")
    get(candidate, "outcome", nothing) == "passed" ||
        fail("publication candidate did not pass")
    get(candidate, "scope", nothing) == "representative" || fail(
        "only Representative references can be published by this operation",
    )
    generation = get(candidate, "generation", nothing)
    generation isa AbstractString &&
        occursin(r"^[A-Za-z0-9][A-Za-z0-9._-]*$", generation) ||
        fail("publication candidate has an invalid generation")
    change_kind = get(candidate, "change_kind", nothing)
    change_kind in ("shared", "model") ||
        fail("publication candidate has an invalid change kind")
    raw_models = get(candidate, "models", nothing)
    raw_models isa AbstractVector || fail("publication candidate lacks models")
    models = String.(raw_models)
    length(models) == length(unique(models)) &&
        all(model -> model in MODELS, models) ||
        fail("publication candidate has invalid models")
    if change_kind == "shared"
        models == collect(MODELS) ||
            fail("shared publication requires all five models")
    else
        length(models) == 1 ||
            fail("model-only publication requires exactly one model")
        isdir(joinpath(candidate_root, "forcing")) &&
            fail("model-only publication must not replace shared forcing")
    end
    model_directories = sort(
        filter(
            name ->
                startswith(name, "model-") &&
                    isdir(joinpath(candidate_root, name)),
            readdir(candidate_root),
        ),
    )
    model_directories == sort(map(model -> "model-$model", models)) ||
        fail("publication candidate contains a partially mixed model set")

    bundles = Any[]
    if change_kind == "shared"
        push!(
            bundles,
            validate_payload(
                joinpath(candidate_root, "forcing"),
                "forcing",
                generation,
            ),
        )
    end
    for model in models
        push!(
            bundles,
            validate_payload(
                joinpath(candidate_root, "model-$model", "reference"),
                "reference",
                generation;
                model,
            ),
        )
    end
    identities = unique(getproperty.(bundles, :compatibility_identity))
    length(identities) == 1 ||
        fail("publication candidate is not one compatibility set")
    return (;
        generation,
        change_kind,
        models,
        bundles,
        compatibility_identity = only(identities),
    )
end

function validate_existing_compatibility(
    expected_manifest_directory,
    artifacts_toml,
)
    isnothing(expected_manifest_directory) &&
        fail("model-only publication requires the existing expected manifests")
    bindings = parse_toml(artifacts_toml, "existing artifact bindings")
    all(
        name -> haskey(bindings, name),
        ("representative_forcing", values(BINDINGS)...),
    ) || fail(
        "existing artifact bindings do not contain a complete compatibility set",
    )
    identities = String[]
    for model in MODELS
        binding = BINDINGS[model]
        manifest = parse_toml(
            joinpath(expected_manifest_directory, "$binding.toml"),
            "$model expected reference manifest",
        )
        provenance = validate_provenance(
            get(manifest, "provenance", nothing),
            "$model expected reference manifest",
        )
        recorded = get(manifest, "compatibility_identity", nothing)
        calculated = compatibility_identity(provenance)
        recorded == calculated || fail(
            "$model expected reference manifest has stale compatibility provenance",
        )
        push!(identities, calculated)
    end
    length(unique(identities)) == 1 ||
        fail("existing expected manifests are a partially mixed generation")
    return only(unique(identities))
end

function binding_name(bundle)
    return bundle.kind == "forcing" ? "representative_forcing" :
           BINDINGS[bundle.model]
end

function copy_payload(source, destination)
    for name in readdir(source)
        cp(joinpath(source, name), joinpath(destination, name); force = true)
    end
    return nothing
end

function create_archive(bundle, asset_directory, generation)
    tree_hash = Pkg.Artifacts.create_artifact() do artifact_directory
        copy_payload(bundle.payload, artifact_directory)
    end
    tree_sha1 = bytes2hex(tree_hash.bytes)
    binding = binding_name(bundle)
    filename = "$generation-$binding-$tree_sha1.tar.gz"
    archive = joinpath(asset_directory, filename)
    sha256 = Pkg.Artifacts.archive_artifact(tree_hash, archive)
    chmod(archive, 0o444)
    return (; binding, filename, tree_hash, tree_sha1, sha256)
end

function write_expected_manifest(path, bundle, archive, release_base_url)
    manifest = deepcopy(bundle.manifest)
    manifest["compatibility_identity"] = bundle.compatibility_identity
    manifest["artifact"] = Dict(
        "binding" => archive.binding,
        "filename" => archive.filename,
        "git_tree_sha1" => archive.tree_sha1,
        "sha256" => archive.sha256,
        "url" => "$release_base_url/$(archive.filename)",
    )
    open(path, "w") do io
        TOML.print(io, manifest; sorted = true)
    end
    return manifest
end

function stage_publication(
    candidate_root,
    output,
    artifacts_toml,
    release_base_url;
    expected_manifest_directory = nothing,
)
    ispath(output) &&
        fail("publication output already exists and cannot be overwritten")
    occursin(
        r"^https://github\.com/[^/]+/[^/]+/releases/download/[^/?#]+$",
        release_base_url,
    ) || fail("release base URL must identify one immutable GitHub release")
    parse_toml(artifacts_toml, "existing artifact bindings")
    candidate = validate_candidate(abspath(candidate_root))
    if candidate.change_kind == "model"
        existing_identity = validate_existing_compatibility(
            expected_manifest_directory,
            artifacts_toml,
        )
        candidate.compatibility_identity == existing_identity || fail(
            "model-only publication differs from the existing compatibility set",
        )
    end

    output = abspath(output)
    parent = dirname(output)
    mkpath(parent)
    staging =
        mktempdir(parent; prefix = ".reference-publication-", cleanup = false)
    completed = false
    try
        assets = joinpath(staging, "assets")
        manifests = joinpath(staging, "manifests")
        mkpath(assets)
        mkpath(manifests)
        staged_artifacts = joinpath(staging, "Artifacts.toml")
        cp(artifacts_toml, staged_artifacts; force = true)
        asset_records = Dict{String, Any}[]
        for bundle in candidate.bundles
            archive = create_archive(bundle, assets, candidate.generation)
            url = "$release_base_url/$(archive.filename)"
            Pkg.Artifacts.bind_artifact!(
                staged_artifacts,
                archive.binding,
                archive.tree_hash;
                download_info = [(url, archive.sha256)],
                force = true,
            )
            write_expected_manifest(
                joinpath(manifests, "$(archive.binding).toml"),
                bundle,
                archive,
                release_base_url,
            )
            push!(
                asset_records,
                Dict(
                    "binding" => archive.binding,
                    "filename" => archive.filename,
                    "git_tree_sha1" => archive.tree_sha1,
                    "sha256" => archive.sha256,
                    "url" => url,
                ),
            )
        end
        open(joinpath(staging, "publication.toml"), "w") do io
            TOML.print(
                io,
                Dict(
                    "schema_version" => 1,
                    "operation" => "reference_publication",
                    "scope" => "representative",
                    "generation" => candidate.generation,
                    "change_kind" => candidate.change_kind,
                    "models" => candidate.models,
                    "compatibility_identity" =>
                        candidate.compatibility_identity,
                    "atomic_compatibility_set" =>
                        candidate.change_kind == "shared",
                    "asset" => asset_records,
                );
                sorted = true,
            )
        end
        ispath(output) &&
            fail("publication output appeared before the atomic commit")
        mv(staging, output)
        completed = true
    finally
        completed || (ispath(staging) && rm(staging; recursive = true))
    end
    return (;
        output,
        generation = candidate.generation,
        models = candidate.models,
    )
end

function main(args = ARGS)
    4 <= length(args) <= 6 || fail(
        "usage: reference_publication.jl stage CANDIDATE OUTPUT RELEASE_BASE_URL [ARTIFACTS_TOML [EXPECTED_MANIFEST_DIRECTORY]]",
    )
    first(args) == "stage" ||
        fail("only the explicit stage operation is supported")
    candidate, output, release_base_url = args[2:4]
    artifacts_toml = length(args) >= 5 ? args[5] : DEFAULT_ARTIFACTS_TOML
    expected_manifest_directory = length(args) == 6 ? args[6] : nothing
    stage_publication(
        candidate,
        output,
        artifacts_toml,
        release_base_url;
        expected_manifest_directory,
    )
    return 0
end

end

if abspath(PROGRAM_FILE) == @__FILE__
    try
        exit(TestbedReferencePublication.main())
    catch error
        error isa TestbedReferencePublication.PublicationError || rethrow()
        println(stderr, "ERROR: ", sprint(showerror, error))
        exit(2)
    end
end
